apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: knet
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/Tim-0731-Hzt/knet/releases/download/v0.1.0/knet_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./knet"
      to: "."
    - from: LICENSE
      to: "."
    bin: "knet"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/Tim-0731-Hzt/knet/releases/download/v0.1.0/knet_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./knet"
      to: "."
    - from: LICENSE
      to: "."
    bin: "knet"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/Tim-0731-Hzt/knet/releases/download/v0.1.0/knet_windows_amd64.zip
    sha256: ""
    files:
    - from: "/knet.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "knet.exe"
  shortDescription: A new plugin
  homepage: https://github.com/Tim-0731-Hzt/knet
  caveats: |
    Usage:
      $ kubectl knet

    For additional options:
      $ kubectl knet --help
      or https://github.com/Tim-0731-Hzt/knet/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
